CREATE DATABASE temp1;
DROP DATABASE temp1;
create database temp2;
drop database temp2;

CREATE DATABASE College;

CREATE DATABASE IF NOT EXISTS College;

USE College;

CREATE TABLE Student (
	id INT PRIMARY KEY,
    name VARCHAR(50),
    age INT NOT NULL
);

INSERT INTO Student VALUES(1,"RAM",26);
INSERT INTO Student VALUES(2,"SHAM",24);

SELECT * FROM Student;

DROP DATABASE Company;

DROP DATABASE IF EXISTS Company;

DROP DATABASE IF EXISTS ABC;

SHOW TABLES;

